#!/usr/bin/env python
"""Sync the Drizzle ORM docs snapshot into this skill.

Downloads https://orm.drizzle.team/llms-full.txt — the concatenation of every
docs page, each introduced by a top-level `# ` heading — and splits it into one
file per page under `references/docs/`, with a routing index next to it.

Drizzle serves no per-page markdown (`.../docs/overview.md` is a 404), so
splitting the full feed is the only way to get a file-per-topic snapshot.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import urllib.request
from pathlib import Path

DEFAULT_URL = "https://orm.drizzle.team/llms-full.txt"
LICENSE_NOTE = "Drizzle ORM docs are Apache-2.0 (https://github.com/drizzle-team/drizzle-orm-docs)"
USER_AGENT = "aetherfield-skill-sync"

FENCE_RE = re.compile(r"^\s*(```|~~~)")
HEADING_RE = re.compile(r"^# +(.+?)\s*$")


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=180) as response:
        return response.read().decode("utf-8")


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "untitled"


def split_pages(text: str) -> list[tuple[str, str]]:
    """Split on top-level headings, ignoring `#` inside fenced code blocks.

    A shell comment inside a ``` fence is not a heading, and Drizzle's docs are
    full of them — tracking the fence state is what keeps the split honest.
    """
    pages: list[tuple[str, str]] = []
    title: str | None = None
    body: list[str] = []
    in_fence = False

    for line in text.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
        if not in_fence:
            match = HEADING_RE.match(line)
            if match:
                if title is not None:
                    pages.append((title, "\n".join(body).strip()))
                title = match.group(1)
                body = []
                continue
        body.append(line)

    if title is not None:
        pages.append((title, "\n".join(body).strip()))
    return pages


def write_snapshot(pages: list[tuple[str, str]], docs_dir: Path, index_out: Path, url: str) -> None:
    if docs_dir.exists():
        shutil.rmtree(docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)

    index_lines = [
        "# Drizzle docs index",
        "",
        f"Generated by `scripts/sync_drizzle_docs.py` from {url}.",
        "Each row is `file — page title`. Load only the file you need.",
        "",
    ]

    for number, (title, body) in enumerate(pages, start=1):
        name = f"{number:03d}-{slugify(title)}.md"
        (docs_dir / name).write_text(f"# {title}\n\n{body}\n", encoding="utf-8")
        index_lines.append(f"- `docs/{name}` — {title}")

    index_lines.append("")
    index_out.write_text("\n".join(index_lines), encoding="utf-8")


def write_source_file(path: Path, url: str, page_count: int, snapshot_date: str) -> None:
    content = "\n".join(
        [
            "Status: Initialized",
            f"Source: {url}",
            f"Pages: {page_count}",
            f"Snapshot-Date: {snapshot_date}",
            f"License: {LICENSE_NOTE}",
            "Note: Re-run scripts/sync_drizzle_docs.py to refresh.",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=DEFAULT_URL)
    args = parser.parse_args()

    skill_root = Path(__file__).resolve().parents[1]
    references_dir = skill_root / "references"
    references_dir.mkdir(parents=True, exist_ok=True)

    text = fetch(args.url)
    pages = split_pages(text)
    if not pages:
        raise SystemExit(f"No top-level headings found in {args.url}; the feed's shape has changed.")

    write_snapshot(pages, references_dir / "docs", references_dir / "docs-index.md", args.url)
    write_source_file(
        references_dir / "docs-source.txt",
        args.url,
        len(pages),
        dt.date.today().isoformat(),
    )
    print(f"Wrote {len(pages)} pages to {references_dir / 'docs'}")


if __name__ == "__main__":
    main()
