#!/usr/bin/env python
"""Sync the Drizzle ORM docs snapshot into this skill.

Downloads https://orm.drizzle.team/llms-full.txt — the concatenation of every
docs page — and splits it into one file per page under `references/docs/`, with
a routing index next to it.

Drizzle serves no per-page markdown (`.../docs/overview.md` is a 404), so
splitting the full feed is the only way to get a file-per-topic snapshot.

**The split is on the feed's own `Source:` stamps, not on `#` headings.** Each
page in the feed is introduced by a `Source: https://orm.drizzle.team/...` line
carrying its canonical URL, and that delimiter is immune to the two problems
headings have here:

1. A `#` shell comment inside a fenced code block looks exactly like a heading.
   Tracking fences is supposed to handle that, but the feed contains a
   malformed *orphan* opening fence (a bare ``` at feed line 1101 whose closer
   is a ```ts), which desynchronises any fence tracker for the remaining
   ~119,000 lines. Splitting on headings therefore invented pages out of shell
   comments and merged real pages away — one file ended up holding 81 of them.
2. Titles repeat across dialects. `drizzle-kit generate` has a Postgres, MySQL,
   CockroachDB and SingleStore page, all with the same H1. The URL disambiguates
   them; the heading cannot.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import urllib.request
from pathlib import Path

DEFAULT_URL = "https://orm.drizzle.team/llms-full.txt"
LICENSE_NOTE = "Drizzle ORM docs are Apache-2.0 (https://github.com/drizzle-team/drizzle-orm-docs)"
USER_AGENT = "aetherfield-skill-sync"

SOURCE_RE = re.compile(r"^Source:\s+(https://orm\.drizzle\.team/\S*)\s*$")
HEADING_RE = re.compile(r"^# +(.+?)\s*$")


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=180) as response:
        return response.read().decode("utf-8")


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "untitled"


def slug_from_url(url: str) -> str:
    """`https://orm.drizzle.team/docs/pg/drizzle-kit-generate` -> `pg-drizzle-kit-generate`.

    The dialect segment is kept deliberately: it is the only thing separating
    four identically titled `drizzle-kit generate` pages.
    """
    path = url.split("orm.drizzle.team/", 1)[-1]
    path = re.sub(r"^docs/", "", path)
    return slugify(path)


def split_pages(text: str) -> list[tuple[str, str, str]]:
    """Return (title, url, body) per page, split on the feed's `Source:` stamps."""
    pages: list[tuple[str, str, str]] = []
    url: str | None = None
    body: list[str] = []

    def flush() -> None:
        if url is None:
            return
        content = "\n".join(body).strip()
        title = next(
            (m.group(1) for m in (HEADING_RE.match(line) for line in body) if m),
            slug_from_url(url).replace("-", " "),
        )
        pages.append((title, url, content))

    for line in text.splitlines():
        match = SOURCE_RE.match(line)
        if match:
            flush()
            url = match.group(1)
            body = []
            continue
        body.append(line)

    flush()
    return pages


def write_snapshot(
    pages: list[tuple[str, str, str]], docs_dir: Path, index_out: Path, url: str
) -> None:
    if docs_dir.exists():
        shutil.rmtree(docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)

    index_lines = [
        "# Drizzle docs index",
        "",
        f"Generated by `scripts/sync_drizzle_docs.py` from {url}.",
        "Each row is `file — title — canonical URL`. Load only the file you need.",
        "",
        "**Titles repeat across dialects.** This project is Postgres: prefer a",
        "`pg-` file, and read the URL rather than the title when choosing.",
        "",
    ]

    for number, (title, page_url, body) in enumerate(pages, start=1):
        name = f"{number:03d}-{slug_from_url(page_url)}.md"
        header = f"# {title}\n\nSource: {page_url}\n\n"
        (docs_dir / name).write_text(header + body + "\n", encoding="utf-8")
        index_lines.append(f"- `docs/{name}` — {title} — {page_url}")

    index_lines.append("")
    index_out.write_text("\n".join(index_lines), encoding="utf-8")


def write_source_file(path: Path, url: str, page_count: int, snapshot_date: str) -> None:
    content = "\n".join(
        [
            "Status: Initialized",
            f"Source: {url}",
            f"Pages: {page_count}",
            "Split-On: the feed's own 'Source: <url>' stamps, not '#' headings",
            f"Snapshot-Date: {snapshot_date}",
            f"License: {LICENSE_NOTE}",
            "Note: Re-run scripts/sync_drizzle_docs.py to refresh.",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=DEFAULT_URL)
    args = parser.parse_args()

    skill_root = Path(__file__).resolve().parents[1]
    references_dir = skill_root / "references"
    references_dir.mkdir(parents=True, exist_ok=True)

    text = fetch(args.url)
    pages = split_pages(text)
    if not pages:
        raise SystemExit(
            f"No 'Source: https://orm.drizzle.team/...' stamps found in {args.url}; "
            "the feed's shape has changed and the split needs re-deriving."
        )

    write_snapshot(pages, references_dir / "docs", references_dir / "docs-index.md", args.url)
    write_source_file(
        references_dir / "docs-source.txt",
        args.url,
        len(pages),
        dt.date.today().isoformat(),
    )
    print(f"Wrote {len(pages)} pages to {references_dir / 'docs'}")


if __name__ == "__main__":
    main()
